### ISSUE TITLE
Finetune on own custom dataset

### ISSUE THREAD

**Issue by gillesmeyhi** [RicherMans/SAT#4]
Hi, thanks for your amazing contributions!

I would love to finetune this model on my own custom dataset consisting of only 2 classes.
My question to you is how do I need to prepare my dataset?

I see that in SAT training you use the WeakHDF5DatasetTextLogits for training and the WeakHDF5Dataset for testing?
I am guessing that is the distinction between full context training and SAT training?

How do I handle varying input sizes? (>2s but <10s) --> for full context training?

**Comment by RicherMans** [comment]
Hey there @gillesmeyhi ,
Actually you don't need any of the datasets in this repo for fine-tuning.
The simplest form that I can think of is :

```python
class AudioDataset(torch.utils.data.Dataset):                                                                                                                                              
                                                                                                                                                                                                
      def __init__(self, data:List[Tuple[str,int]]) -> None:                                                                                                                                             
          super().__init__()                                                                                                                                                                   
          self.data = data
                                                                                                                                                                                                
      def __getitem__(self, index):                                                                                                                                                             
          filename, label = self.data[index]                                                                                                                                                    
          audio = torchaudio.load(filename)[0]                                                                                                                                                  
          return audio, torch.tensor(label)                                                                                                                                             
                                                                                                                                                                                                
      def __len__(self):                                                                                                                                                                        
          return len(self.data) 

dataset =AudioDataset([('some_sample_path.wav', 0), ('some_sample_path2.wav', 1)])
```


> I see that in SAT training you use the WeakHDF5DatasetTextLogits for training and the WeakHDF5Dataset for testing?
I am guessing that is the distinction between full context training and SAT training?

Correct. You can also train with WeakHDF5Dataset, but its rather slow ( sequentially going over 5 to 10 chunks).

> How do I handle varying input sizes? (>2s but <10s) --> for full context training?

Two ways: 
First you could implement mask padding into the self-attention. I am just a bit too lazy to do that. That mask padding will be according to the data samples length i.e., remove the impact of padding when data is too variable.
Second, follow the guidelines of this paper, i.e., it would be best to first pretrain a teacher that can give guidance for that  specific range of durations you need. What I mean by that is do not use methods that do not support variable length inputs, since they completely fail.

Just the record, SAT is mainly focused for real-world applications and not tailored towards "best performance on dataset x".
Kind regards,
Heinrich

**Comment by gillesmeyhi** [comment]
Hi @RicherMans, thank you for responding! I am trying to run the 1_run_mae script at the moment (on my own data), but I run into the following error:

```
/xxxxx/xxxxxx/miniconda3/envs/sat/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
[2024-03-20 15:51:29] Got 15196 train samples and 3799 validation ones.
[2024-03-20 15:51:29] Using warmup with 45588 iters
Current run is terminating due to exception: name 'str2optimizer32bit' is not defined
Engine run is terminating due to exception: name 'str2optimizer32bit' is not defined


NameError: name 'str2optimizer32bit' is not defined
``` 

I can not seem to find a (working) solution to this issue elsewhere, do you have an idea of what this could be?

Kind regards,
Gilles

**Comment by RicherMans** [comment]
Hey @gillesmeyhi ,
First I just recommend using my own checkpoints for the MAE. 
I don't think that switching the data will lead to a great improvement in performance overall.
I already did quite some experimentation and as it turns out the MAE part is only responsible for "bootstrapping" the model i.e., letting it know what different patches in the time-frequency region refer to.

Second the error you mention is due to a wrong installation of [bitsandbytes](https://github.com/TimDettmers/bitsandbytes).
I personally use these optimizers since they save a bit of GPU memory and thus allow me to run more jobs.
As a quick fix, just pass `--optimizer Adam` or `AdamW`, they should work without a problem.

Kind regards,
Heinrich

**Comment by gillesmeyhi** [comment]
> As a quick fix, just pass --optimizer Adam or AdamW, they should work without a problem.

This worked like a charm, I wasted too much time trying to install bitsandbytes correctly 🥲

> First I just recommend using my own checkpoints for the MAE.
I don't think that switching the data will lead to a great improvement in performance overall.
I already did quite some experimentation and as it turns out the MAE part is only responsible for "bootstrapping" the model i.e., letting it know what different patches in the time-frequency region refer to.

Ok, so I finetune your pretrained audiotransformer_base(/small/tiny) model with my own data, then get pseudo-strong-labels for this data and then use 2_train_sat.py with my own data and own psl to finetune the streaming transformer?

Kind regards,
Gilles

**Comment by RicherMans** [comment]
Hey @gillesmeyhi 

> Ok, so I finetune your pretrained audiotransformer_base(/small/tiny) model with my own data, then get pseudo-strong-labels for this data and then use 2_train_sat.py with my own data and own psl to finetune the streaming transformer? 

Yeah you can do that, however I thought that your data is already at some lower duration than audioset, say 1s with corresponding labels.

If that would be the case I recommend you to use the original labels + the PSL labels generated from one of my models as training targets.

Kind regards,
Heinrich
